### helth check
GET http://localhost:4004/

### register
POST http://localhost:4004/auth/register
Content-Type: application/json
User-Agent: "res-client"

{
    "email": "test1@gmail.com",
    "password": "123456",
    "confirmPassword": "123456"
}

### login
POST http://localhost:4004/auth/login
Content-Type: application/json
User-Agent: "res-client"

{
   "email": "test@gmail.com",
   "password": "123456"
}

### logout
POST http://localhost:4004/auth/logout
User-Agent: "res-client"


### refresh token
GET http://localhost:4004/auth/refresh
User-Agent: "res-client"

### email verification
GET http://localhost:4004/auth/email/verify/67f9c8980676ec9672ffe639
User-Agent: "res-client"


### forgot-password
POST http://localhost:4004/auth/password/forgot
Content-Type: application/json
User-Agent: "res-client"

{
    "email": "alhdrin97@gmail.com"
}

### reset password
POST http://localhost:4004/auth/password/reset
Content-Type: application/json
User-Agent: "res-client"

{
    "verificationCode": "67f7cf046a72025283fb9200",
    "password": "111111"
}

### get user details
GET http://localhost:4004/user
Content-Type: application/json
User-Agent: "res-client"

### get all sessions
GET http://localhost:4004/session
Content-Type: application/json
User-Agent: "res-client"

### delete session
DELETE  http://localhost:4004/session/67f9fc7d641db4baa6d5a53c
Content-Type: application/json
User-Agent: "res-client"
